name: ImgRegPytorchProject-env
channels:
  - defaults
dependencies:
  - python=3.11
  - pip=24.0
  - setuptools
  - openssl
  - pip:
      - absl-py==2.1.0
      - asttokens==2.4.1
      - chex==0.1.86
      - colorama==0.4.6
      - contourpy==1.2.1
      - cycler==0.12.1
      - debugpy==1.8.1
      - decorator==5.1.1
      - diffrax==0.5.1
      - equinox==0.11.4
      - executing==2.0.1
      - filelock==3.14.0
      - fonttools==4.52.4
      - functorch==2.0.0
      - ipykernel==6.29.4
      - ipython==8.25.0
      - jax==0.4.30
      - jaxlib==0.4.30
      - jaxopt==0.8.3
      - jedi==0.19.1
      - joblib==1.4.2
      - kiwisolver==1.4.5
      - lineax==0.0.5
      - matplotlib==3.9.0
      - ml-dtypes==0.4.0
      - mpmath==1.3.0
      - networkx==3.3
      - numpy==1.26.4
      - opt-einsum==3.3.0
      - optax==0.2.2
      - optimistix==0.0.7
      - pandas==2.2.2
      - pillow==10.3.0
      - prompt-toolkit==3.0.45
      - psutil==5.9.8
      - pygments==2.18.0
      - pyparsing==3.1.2
      - pytz==2024.1
      - pyzmq==26.0.3
      - scikit-learn==1.5.1
      - scipy==1.13.1
      - six==1.16.0
      - sympy==1.12
      - threadpoolctl==3.5.0
      - torch==2.0.1
      - torchdiffeq==0.2.3
      - torchimize==0.0.16
      - tornado==6.4
      - tqdm==4.66.4
      - traitlets==5.14.3
      - typeguard==2.13.3
      - typing-extensions==4.12.0
      - tzdata==2024.1
      - wcwidth==0.2.13
